#!/bin/bash

#installs solr and mongo connector


apt-get update
apt-get install default-jre
apt-get install default-jdk
wget http://download.nextag.com/apache/lucene/solr/5.3.0/solr-5.3.0.tgz
tar -zxvf solr-5.3.0.tgz

apt-get install python-pip
pip install mongo-connector

